/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jondrew' at '4/13/16 3:56 PM' with Gradle 2.10
 *
 * @author jondrew, @date 4/13/16 3:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
